#!/bin/bash

protoc proto/*.proto \
    --proto_path=. \
    --go_out=./internal/api --go_opt=paths=source_relative \
    --go-grpc_out=./internal/api --go-grpc_opt=paths=source_relative \
    --plugin=$HOMEBREW_PREFIX/bin/protoc-gen-swift \
    --swift_opt=Visibility=Public \
    --swift_out=Shared/Model \
    --plugin=$HOMEBREW_PREFIX/bin/protoc-gen-grpc-swift \
    --grpc-swift_opt=Visibility=Public \
    --grpc-swift_out=Shared/Model
